# CANONICAL LABEL DEFINITIONS - Source of Truth
# Synced by .github/workflows/label-sync.yml
# Governance: See docs/governance/ for label policies
#
# Rules:
# - Every issue MUST have ONE priority + ONE pillar + ONE type
# - Module/status labels are optional
# - This file = truth. Unlisted labels get deleted.

# ═══════════════════════════════════════════════════════════════
# PRIORITY (mutually exclusive - pick ONE)
# ═══════════════════════════════════════════════════════════════
- name: P0
  color: "B60205"
  description: "Production broken - fix immediately"

- name: P1
  color: "D93F0B"
  description: "Blocks launch - fix this sprint"

- name: P2
  color: "FBCA04"
  description: "Should do - this month"

- name: P3
  color: "0E8A16"
  description: "Backlog - someday maybe"

# ═══════════════════════════════════════════════════════════════
# PILLAR (mutually exclusive - pick ONE)
# ═══════════════════════════════════════════════════════════════
- name: mint-os
  color: "98FB98"
  description: "Print shop management system"

- name: infrastructure
  color: "1D76DB"
  description: "Servers, networking, DevOps"

- name: homelab
  color: "1E90FF"
  description: "Home automation, Proxmox"

- name: media-stack
  color: "7B68EE"
  description: "Jellyfin, *arr suite"

- name: immich
  color: "FF6B6B"
  description: "Photo management"

- name: finance
  color: "8B4513"
  description: "Firefly III, Ghostfolio"

# ═══════════════════════════════════════════════════════════════
# TYPE (mutually exclusive - pick ONE)
# ═══════════════════════════════════════════════════════════════
- name: bug
  color: "B60205"
  description: "Something is broken"

- name: feature
  color: "0E8A16"
  description: "New functionality"

- name: debt
  color: "FEF2C0"
  description: "Tech debt cleanup"

- name: docs
  color: "0075ca"
  description: "Documentation"

# ═══════════════════════════════════════════════════════════════
# MODULE (optional - can have multiple)
# ═══════════════════════════════════════════════════════════════
- name: shipping
  color: "BFD4F2"
  description: "Shipping module"

- name: pricing
  color: "BFD4F2"
  description: "Pricing module"

- name: suppliers
  color: "BFD4F2"
  description: "Supplier sync"

- name: artwork
  color: "BFD4F2"
  description: "Artwork processing"

- name: files
  color: "BFD4F2"
  description: "File management"

- name: database
  color: "BFD4F2"
  description: "Database schema"

- name: minio
  color: "BFD4F2"
  description: "MinIO storage"

- name: standalone
  color: "BFD4F2"
  description: "Standalone app deployment"

# ═══════════════════════════════════════════════════════════════
# STATUS (optional - workflow state)
# ═══════════════════════════════════════════════════════════════
- name: blocked
  color: "000000"
  description: "Waiting on external dependency"

- name: needs-spec
  color: "D4C5F9"
  description: "Requirements missing"

- name: needs-verification
  color: "D4C5F9"
  description: "Done, needs testing"

- name: audit
  color: "FBCA04"
  description: "Audit/discovery task"

- name: epic
  color: "3E4B9E"
  description: "Large multi-issue effort"

- name: human-action
  color: "C2E0C6"
  description: "Requires manual/physical action"

# ═══════════════════════════════════════════════════════════════
# SPECIAL
# ═══════════════════════════════════════════════════════════════
- name: spark
  color: "5319E7"
  description: "Good for GitHub Spark"

- name: spark-candidate
  color: "D4C5F9"
  description: "Candidate for Spark framework"
