#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../../.." && pwd)"
SCRIPT="$ROOT/ops/plugins/core/loops/bin/loop-closeout-finalize"

PASS=0
FAIL=0

pass() { PASS=$((PASS + 1)); echo "PASS: $1"; }
fail() { FAIL=$((FAIL + 1)); echo "FAIL: $1" >&2; }

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

runtime="$tmpdir/runtime"
scope_dir="$runtime/state/loop-scopes"
mkdir -p "$scope_dir"

loop_id="LOOP-CLOSEOUT-RUNKEY-HANDOFF-TEST"
scope_file="$scope_dir/${loop_id}.scope.md"
matrix_file="$tmpdir/ACCEPTANCE_MATRIX.md"
receipt_file="$tmpdir/closeout-receipt.md"
run_key="CAP-20260330-023900__wave.finish__Rfixture01"

cat > "$scope_file" <<EOF
---
loop_id: $loop_id
status: active
owner: '@ronny'
execution_mode: orchestrator_subagents
execution_readiness: runnable
objective: loop closeout run-key handoff test
---
EOF

cat > "$matrix_file" <<EOF
# Wave Finish Acceptance Matrix
# Generated by wave.finish for $loop_id

decision: DONE
blocker_count: 0

| check | surface | result | detail |
|-------|---------|--------|--------|
| runtime_agreement | runtime | PASS | fixture runtime |
| control_plane_agreement | control-plane | PASS | fixture control |
| projection_agreement | projections | PASS | fixture projection |
| residue_check | residue | PASS | fixture residue |

run_key: $run_key

# Contract-valid run key lines for loop-closeout-finalize validation.
$run_key
EOF

output="$(
  env SPINE_RUNTIME_ROOT="$runtime" SPINE_STATE="$runtime/state" \
    bash "$SCRIPT" \
      --loop-id "$loop_id" \
      --acceptance-matrix "$matrix_file" \
      --disposition deferred \
      --propagation-evidence "fixture propagation evidence" \
      --receipt-path "$receipt_file" \
      --no-close-linked-gaps 2>&1
)" || {
  echo "$output"
  fail "loop-closeout-finalize accepts wave-finish run-key handoff"
  echo "PASS: $PASS"
  echo "FAIL: $FAIL"
  exit 1
}

pass "loop-closeout-finalize accepts wave-finish run-key handoff"

python3 - <<'PY' "$receipt_file" "$scope_file"
import pathlib
import sys

receipt = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
scope = pathlib.Path(sys.argv[2]).read_text(encoding="utf-8")
assert "- matrix_run_key_count: 1" in receipt, receipt
assert "status: closed" in scope, scope
PY
pass "closeout receipt records one accepted run key and loop closes"

echo "PASS: $PASS"
echo "FAIL: $FAIL"

if [[ "$FAIL" -ne 0 ]]; then
  exit 1
fi
