name: Spine Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  drift-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Run drift gates
        run: bash surfaces/verify/drift-gate.sh
        env:
          SPINE_ROOT: ${{ github.workspace }}
          SPINE_REPO: ${{ github.workspace }}
