# Docker Compose Targets Binding (SSOT)
# Non-secret. Spine-native. No monolith runtime dependency.
# Status: projection
# authority_state: projection
# authority_concern: service_registry_surfaces
# projection_of: docs/governance/SERVICE_REGISTRY.yaml
# Last verified: 2026-02-22
#
# Discovered from actual stack directories on each host.

version: 1

targets:
  docker-host:
    ssh_target: docker-host
    connect_timeout_sec: 5
    enabled: true
    description: "Mint OS frontends (customer/admin/production/kanban) are active. Dashy migrated to observability VM 205. Finance migrated to finance-stack VM 211; mail-archiver canonicalized to communications-stack VM 214. API is deprecated. Legacy standalone storage stack retired; MinIO runs under mint-os compose."
    stacks:
      - name: mint-os
        path: /home/docker-host/stacks/mint-os
      - name: mint-modules-prod
        path: /home/docker-host/mint-modules-prod
        legacy_only: true
        authoritative_runtime: false
        # Previously listed as two aliases (artwork-module + quote-page) pointing to same compose project.
        # Merged to match actual Docker project name and stop double-counting. Contains: order-intake, quote-page, files-api.
        # These are legacy duplicates of services now live on mint-apps VM 213.
      # dashy MIGRATED to observability VM 205 (LOOP-OBSERVABILITY-DOMAIN-ENRICHMENT-20260226)
      # finance DECOMMISSIONED on docker-host — migrated to finance-stack VM 211
      # mail-archiver DECOMMISSIONED on docker-host — canonicalized to communications-stack VM 214

  infra-core:
    ssh_target: infra-core
    connect_timeout_sec: 5
    stacks:
      - name: cloudflared
        path: /opt/stacks/cloudflared
      - name: pihole
        path: /opt/stacks/pihole
      - name: secrets
        path: /opt/stacks/secrets
      - name: vaultwarden
        path: /opt/stacks/vaultwarden
      - name: caddy-auth
        path: /opt/stacks/caddy-auth

  # media-stack (VM 201) DECOMMISSIONED 2026-02-10 — split into download-stack + streaming-stack

  download-stack:
    ssh_target: download-stack
    connect_timeout_sec: 5
    stacks:
      - name: download-stack
        path: /opt/stacks/download-stack

  streaming-stack:
    ssh_target: streaming-stack
    connect_timeout_sec: 5
    stacks:
      - name: streaming-stack
        path: /opt/stacks/streaming-stack

  immich:
    ssh_target: immich
    connect_timeout_sec: 5
    description: "Immich photo management VM 203 (user=ronny). 4 containers: server, ML, postgres, redis."
    stacks:
      - name: immich
        path: ~/immich

  ai-consolidation:
    ssh_target: ai-consolidation
    connect_timeout_sec: 5
    stacks:
      - name: ai-consolidation
        path: /opt/stacks/ai-consolidation

  observability:
    ssh_target: observability
    connect_timeout_sec: 5
    stacks:
      - name: prometheus
        path: /opt/stacks/prometheus
      - name: grafana
        path: /opt/stacks/grafana
      - name: loki
        path: /opt/stacks/loki
      - name: uptime-kuma
        path: /opt/stacks/uptime-kuma
      - name: node-exporter
        path: /opt/stacks/node-exporter
      - name: dashy
        path: /opt/stacks/dashy

  dev-tools:
    ssh_target: dev-tools
    connect_timeout_sec: 5
    stacks:
      - name: gitea
        path: /opt/stacks/gitea

  automation-stack:
    ssh_target: automation-stack
    connect_timeout_sec: 5
    stacks:
      - name: automation
        path: /home/automation/stacks/automation
      - name: mcpjungle
        path: /home/automation/stacks/mcpjungle

  finance-stack:
    ssh_target: finance-stack
    connect_timeout_sec: 5
    enabled: true
    description: "Finance stack VM 211 (Firefly III, Ghostfolio, Paperless-ngx). Mail-archiver is migration_source — canonical runtime now on communications-stack VM 214."
    stacks:
      - name: finance
        path: /opt/stacks/finance

  mint-data:
    ssh_target: mint-data
    connect_timeout_sec: 5
    enabled: true
    description: "Mint data plane VM 212 (fresh-slate). PostgreSQL 16 + MinIO + Redis."
    stacks:
      - name: mint-data
        path: /opt/stacks/mint-data

  mint-apps:
    ssh_target: mint-apps
    connect_timeout_sec: 5
    enabled: true
    description: "Mint app plane VM 213 (fresh-slate). Service stacks: files-api, quote-page, order-intake, finance-adapter, pricing, suppliers, shipping, payment."
    stacks:
      - name: mint-apps
        path: /opt/stacks/mint-apps
      - name: payment
        path: /opt/stacks/mint-apps/payment
      - name: pricing
        path: /opt/stacks/mint-apps/pricing
      - name: suppliers
        path: /opt/stacks/mint-apps/suppliers
      - name: shipping
        path: /opt/stacks/mint-apps/shipping

  communications-stack:
    ssh_target: communications-stack
    connect_timeout_sec: 5
    enabled: true
    description: "Communications stack VM 214 (Stalwart self-hosted mail + mail-archiver). Canonical mail-archiver runtime (LOOP-MAIL-ARCHIVER-COMMS-MIGRATION-20260225)."
    stacks:
      - name: communications-stack
        path: /opt/stacks/communications-stack
      - name: mail-archiver
        path: /opt/stacks/communications-stack

  # ─── Home Site (proxmox-home — Beelink SER7) ──────────────────────────
  # VM 100 (homeassistant): HA OS — uses its own supervisor, NOT docker-compose. Excluded.
  # VM 101 (immich-home): stopped — compose path unverified. Register when started.
  # LXC 103 (download-home): stopped. Register when started.
  # LXC 105 (pihole-home): stopped. May not use docker-compose.

  vaultwarden-home:
    ssh_target: infra-core
    connect_timeout_sec: 10
    enabled: false  # decommissioned 2026-02-16
    description: "DECOMMISSIONED. Vaultwarden (home VM 102). Superseded by infra-core. ssh_target normalized to existing canonical target for lifecycle parity."
    stacks:
      - name: vaultwarden
        path: /home/ron/vaultwarden
