# Docker Compose Targets Binding (SSOT)
# Non-secret. Spine-native. No monolith runtime dependency.
#
# Discovered from actual stack directories on each host.

version: 1

targets:
  docker-host:
    ssh_target: docker-host
    connect_timeout_sec: 5
    stacks:
      - name: mint-os
        path: ~/stacks/mint-os
      - name: finance
        path: ~/stacks/finance
      - name: mail-archiver
        path: ~/stacks/mail-archiver

  infra-core:
    ssh_target: infra-core
    connect_timeout_sec: 5
    stacks:
      - name: cloudflared
        path: /opt/stacks/cloudflared
      - name: pihole
        path: /opt/stacks/pihole
      - name: secrets
        path: /opt/stacks/secrets
      - name: vaultwarden
        path: /opt/stacks/vaultwarden
      - name: caddy-auth
        path: /opt/stacks/caddy-auth

  media-stack:
    ssh_target: media-stack
    connect_timeout_sec: 10
    stacks:
      - name: media-stack
        path: ~/stacks/media-stack
    notes: "Legacy monolith — decommission after LOOP-MEDIA-STACK-SPLIT-20260208 soak"

  download-stack:
    ssh_target: download-stack
    connect_timeout_sec: 5
    stacks:
      - name: download-stack
        path: /opt/stacks/download-stack

  streaming-stack:
    ssh_target: streaming-stack
    connect_timeout_sec: 5
    stacks:
      - name: streaming-stack
        path: /opt/stacks/streaming-stack

  ai-consolidation:
    ssh_target: ai-consolidation
    connect_timeout_sec: 5
    stacks:
      - name: ai-consolidation
        path: /opt/stacks/ai-consolidation

  observability:
    ssh_target: observability
    connect_timeout_sec: 5
    stacks:
      - name: prometheus
        path: /opt/stacks/prometheus
      - name: grafana
        path: /opt/stacks/grafana
      - name: loki
        path: /opt/stacks/loki
      - name: uptime-kuma
        path: /opt/stacks/uptime-kuma
      - name: node-exporter
        path: /opt/stacks/node-exporter

  dev-tools:
    ssh_target: dev-tools
    connect_timeout_sec: 5
    stacks:
      - name: gitea
        path: /opt/stacks/gitea

  automation-stack:
    ssh_target: automation-stack
    connect_timeout_sec: 5
    stacks:
      - name: automation
        path: ~/stacks/automation
      - name: mcpjungle
        path: ~/stacks/mcpjungle
