# Docker Compose Targets Binding (SSOT)
# Non-secret. Spine-native. No ronny-ops runtime dependency.
#
# Discovered from actual stack directories on each host.

version: 1

targets:
  docker-host:
    ssh_target: docker-host
    connect_timeout_sec: 5
    stacks:
      - name: mint-os
        path: ~/stacks/mint-os
      - name: finance
        path: ~/stacks/finance
      - name: cloudflared
        path: ~/stacks/cloudflared
      - name: mail-archiver
        path: ~/stacks/mail-archiver
      - name: mcpjungle
        path: ~/stacks/mcpjungle
      - name: pihole
        path: ~/stacks/pihole
      - name: secrets
        path: ~/stacks/secrets
      - name: storage
        path: ~/ronny-ops/infrastructure/storage

  media-stack:
    ssh_target: media-stack
    connect_timeout_sec: 10
    stacks:
      - name: media-stack
        path: ~/stacks/media-stack

  automation-stack:
    ssh_target: automation-stack
    connect_timeout_sec: 5
    stacks:
      - name: automation
        path: ~/stacks/automation
