# Docker Compose Targets Binding (SSOT)
# Non-secret. Spine-native. No monolith runtime dependency.
#
# Discovered from actual stack directories on each host.

version: 1

targets:
  docker-host:
    ssh_target: docker-host
    connect_timeout_sec: 5
    enabled: true
    notes: "Mint OS frontends (customer/admin/production/kanban) and Dashy dashboard are active. Finance + mail-archiver migrated to finance-stack VM 211. API is deprecated. MinIO canonical via storage stack. artwork-module + quote-page are INTERIM here — fresh-slate target is mint-apps VM (ADR-001)."
    stacks:
      - name: mint-os
        path: ~/stacks/mint-os
      - name: storage
        path: ~/stacks/storage
      - name: artwork-module
        path: ~/artwork-module
        # INTERIM: fresh-slate target is mint-apps VM (ADR-001 in mint-modules)
      - name: quote-page
        path: ~/quote-page
        # INTERIM: fresh-slate target is mint-apps VM (ADR-001 in mint-modules)
      - name: dashy
        path: ~/stacks/dashy
      # finance + mail-archiver DECOMMISSIONED on docker-host — migrated to finance-stack VM 211

  infra-core:
    ssh_target: infra-core
    connect_timeout_sec: 5
    stacks:
      - name: cloudflared
        path: /opt/stacks/cloudflared
      - name: pihole
        path: /opt/stacks/pihole
      - name: secrets
        path: /opt/stacks/secrets
      - name: vaultwarden
        path: /opt/stacks/vaultwarden
      - name: caddy-auth
        path: /opt/stacks/caddy-auth

  # media-stack (VM 201) DECOMMISSIONED 2026-02-10 — split into download-stack + streaming-stack

  download-stack:
    ssh_target: download-stack
    connect_timeout_sec: 5
    stacks:
      - name: download-stack
        path: /opt/stacks/download-stack

  streaming-stack:
    ssh_target: streaming-stack
    connect_timeout_sec: 5
    stacks:
      - name: streaming-stack
        path: /opt/stacks/streaming-stack

  immich:
    ssh_target: immich
    connect_timeout_sec: 5
    notes: "Immich photo management VM 203 (user=ronny). 4 containers: server, ML, postgres, redis."
    stacks:
      - name: immich
        path: ~/immich

  ai-consolidation:
    ssh_target: ai-consolidation
    connect_timeout_sec: 5
    stacks:
      - name: ai-consolidation
        path: /opt/stacks/ai-consolidation

  observability:
    ssh_target: observability
    connect_timeout_sec: 5
    stacks:
      - name: prometheus
        path: /opt/stacks/prometheus
      - name: grafana
        path: /opt/stacks/grafana
      - name: loki
        path: /opt/stacks/loki
      - name: uptime-kuma
        path: /opt/stacks/uptime-kuma
      - name: node-exporter
        path: /opt/stacks/node-exporter

  dev-tools:
    ssh_target: dev-tools
    connect_timeout_sec: 5
    stacks:
      - name: gitea
        path: /opt/stacks/gitea

  automation-stack:
    ssh_target: automation-stack
    connect_timeout_sec: 5
    stacks:
      - name: automation
        path: /home/automation/stacks/automation
      - name: mcpjungle
        path: /home/automation/stacks/mcpjungle

  finance-stack:
    ssh_target: finance-stack
    connect_timeout_sec: 5
    enabled: true
    notes: "Finance stack VM 211 (Firefly III, Ghostfolio, Paperless-ngx, Mail Archiver). Live — migrated from docker-host (LOOP-FINANCE-VM-SEPARATION-20260211)."
    stacks:
      - name: finance
        path: /opt/stacks/finance
