---
status: authoritative
owner: "@ronny"
last_verified: 2026-02-28
scope: spine-execution-graph
version: 1
updated_at: "2026-02-18"
description: "Canonical execution graph for spine core control-plane surfaces."
nodes:
  - id: session
    type: runtime
    description: "Terminal session context and process ownership."
  - id: capability_run
    type: runtime
    description: "Capability execution invocation and result."
  - id: receipt
    type: evidence
    description: "Immutable execution record under receipts/sessions."
  - id: loop_scope
    type: governance
    description: "Repo-authoritative loop scope record."
  - id: gap_registry
    type: governance
    description: "Repo-authoritative operational gap registry entry."
  - id: proposal
    type: runtime
    description: "Proposal lifecycle artifact under runtime outbox."
  - id: orchestration_lane
    type: runtime
    description: "Lane ticket/validation/integration records."
  - id: handoff
    type: runtime
    description: "Cross-session handoff artifact state."
edges:
  - id: session_executes_capability
    from: session
    to: capability_run
    event_type: "session.executes"
    description: "Session executes a capability run."
  - id: capability_emits_receipt
    from: capability_run
    to: receipt
    event_type: "capability.emits_receipt"
    description: "Capability execution writes receipt artifact."
  - id: session_updates_loop_scope
    from: session
    to: loop_scope
    event_type: "session.updates_loop_scope"
    description: "Session updates loop scope state in repo."
  - id: session_updates_gap_registry
    from: session
    to: gap_registry
    event_type: "session.updates_gap_registry"
    description: "Session updates gap registry in repo."
  - id: capability_mutates_proposal
    from: capability_run
    to: proposal
    event_type: "capability.mutates_proposal"
    description: "Proposal capabilities update runtime proposal state."
  - id: capability_mutates_handoff
    from: capability_run
    to: handoff
    event_type: "capability.mutates_handoff"
    description: "Session handoff capability creates or updates handoff state."
  - id: capability_mutates_orchestration_lane
    from: capability_run
    to: orchestration_lane
    event_type: "capability.mutates_orchestration_lane"
    description: "Orchestration capabilities progress lane lifecycle."
views:
  - id: core
    description: "Spine core graph used by spine.graph.show default view."
    include_node_ids:
      - session
      - capability_run
      - receipt
      - loop_scope
      - gap_registry
      - proposal
      - orchestration_lane
      - handoff
    include_edge_ids:
      - session_executes_capability
      - capability_emits_receipt
      - session_updates_loop_scope
      - session_updates_gap_registry
      - capability_mutates_proposal
      - capability_mutates_handoff
      - capability_mutates_orchestration_lane
