version: "1.0"
environment:
  name: ""
  tier: product
  deployed_at: ""

identity:
  org: ""
  role: product
  contact: ""

contracts:
  preflight:
    - read_environment_contract
    - verify_identity
    - check_drift_gates
  restricted:
    - delete_receipts
    - modify_authority_index
    - change_environment_tier
    - register_new_host
  allowed:
    - container_deploy
    - runner_task
    - receipt_write
    - log_append
    - code_change
    - test_run

declared_services: []

drift_gates:
  scope: environment
  categories:
    - identity
    - receipts
    - spine_core
  fail_action: block
