version: "1.0"
environment:
  name: ""
  tier: production
  deployed_at: ""

identity:
  org: ""
  role: brain
  contact: ""

contracts:
  preflight:
    - read_environment_contract
    - verify_identity
    - check_drift_gates
    - verify_secrets_binding
  restricted:
    - delete_receipts
    - modify_authority_index
    - change_environment_tier
    - register_new_host
    - modify_secrets_binding
    - delete_backup
  allowed:
    - container_deploy
    - container_scale
    - runner_task
    - receipt_write
    - log_append
    - backup_create
    - backup_verify

declared_hosts: []
declared_services: []
declared_networks: []

secrets_binding:
  provider: infisical
  project: ""
  environment: production

backup:
  enabled: true
  targets: []
  retention_days: 30

drift_gates:
  scope: environment
  categories:
    - identity
    - environment
    - receipts
    - services
    - spine_core
  fail_action: block

telemetry:
  enabled: true
  endpoint: ""
  interval_seconds: 60
